name: exchange_caclculator
description: A Esteban Ariel Farias Generated Exchange Caclculator.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  dio:
  get_it:
  go_router:
  injectable:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  freezed: 
  freezed_annotation:
  injectable_generator: 
  json_annotation:
  json_serializable:
  pretty_dio_logger:
  retrofit:
  retrofit_generator:

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true
    rive: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/fiat_currencies/
    - assets/cripto_currencies/
   

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
